language: generic
os: osx

matrix:
  include:
    - osx_image: xcode11.2 # MacOS Mojave
    - osx_image: xcode10.1 # MacOS High Sierra
    - osx_image: xcode9.2  # MacOS Sierra

  allow_failures:
    - osx_image: xcode9.2  # Yap weird linking problem
    - osx_image: xcode11.2 # Yap Java problems

before_install:
  - travis_wait 60 softwareupdate -i -a
  - sudo chown -R "$USER" "$(brew --repo)"
  - travis_retry brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"

script:
  - brew test-bot
  - travis_wait 60 brew install --build-bottle Formula/scipoptsuite.rb
  - travis_wait 60 brew install --build-bottle Formula/yap.rb --HEAD
  - brew test Formula/scipoptsuite.rb
  - brew test Formula/yap.rb
