language: generic
os: osx

jobs:
  include:
    - osx_image: xcode11.6 # MacOS 10.15 (Catalina)
    - osx_image: xcode11.3 # MacOS 10.14 (Mojave)
    - osx_image: xcode10.1 # MacOS 10.13 (High Sierra)

before_install:
  - brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"

script:
  - travis_wait 60 brew install --build-bottle Formula/scipoptsuite.rb
  # - travis_wait 60 brew install --build-bottle Formula/yap.rb --HEAD
  - brew test Formula/scipoptsuite.rb
  # - brew test Formula/yap.rb
